-- 1. total revenue generated by male vs female customers

select gender, SUM(purchase_amount) AS revenue
from customers group by gender;

-- total revenue from male is 157890 and from female is 75191

-- 2. which customers used a discount but still spent more than average purchase amount

select customer_id, purchase_amount
from customers
where discount_applied = 'YES' and purchase_amount >= (select avg(purchase_amount) from customers);

select COUNT(*) as discount_applied_more_than_avg_purchase
from customers
where discount_applied = 'YES' and purchase_amount >= (select avg(purchase_amount) from customers);

-- total 839 customers customers used a discount and spent more than average purchase amount

-- 3. Top 5 product with the highest average review rating

select item_purchased, ROUND(AVG(review_rating),2) as average_review from customers group by item_purchased 
order by avg(review_rating) desc limit 5;

-- the top 5 products with highest avg review rating are sandals (3.82), boots (3.79), gloves (3.78), hat (3.78), handbag (3.78)

-- 4. Compare the average purchase amounts between standard and express shipping

select shipping_type, round(avg(purchase_amount), 2) as avg_puchase_amount
from customers 
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- the average puchase amount for standard shipping is 60.48 and for express shipping is 58.46

-- 5. Do subscribed customers spend more ? Compare average spend and total revenue between subscribed and non-subscribed

select subscription_status, ROUND(AVG(purchase_amount),2) as avg_spend , SUM(purchase_amount) as total_revenue
from customers
group by subscription_status;

-- no, unsubscribed customer actual spend more than subscibed ones 
-- the average spending of subscrbed customers is 59.49 whereas 59.87 for unsubscribed, 
-- total revenue of unsubscribed customers is 170436 and for subscibed ones its 62645


-- 6. Which 5 products have the highest percentage of purchases with discount applied

select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

-- the top 5 products with highest purchases with discount applied
-- Hat (50.00)
-- Sneakers (49.66)
-- Coat (49.07)
-- Sweather (48.17)
-- Pants (47.37) 

-- 7. segement customers into new, returning, and loyal based on their total
-- number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE 
 when previous_purchases =1 then "New"
 when previous_purchases between 2 and 10 then "Returning"
 else "Loyal"
 end as customer_segment
from customers
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- there are 3116 loyal customer who purchases more than 10 products
-- there are 701 returning customers between 2 to 10
-- and there are 83 new customers
-- this shows that our store is good in retaining customers
 


-- 8. top 3 products within each category


with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
order by category, item_rank;

-- top 3 items in each category
-- accessories: Jewelry, Sunglasses, and belt
-- clothing: Belt, Blouse, Pants
-- footwear: Sandals, Shoes, Sneakers
-- outerwear: Jacket, Coat

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

select subscription_status, count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

-- we can see that only 958 repeat buyers subscribe where as most of repeat buyers do not subscribe
-- it indicates that our subscription offer is not very attractive

-- 10. revenue contribution of each age group

select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;

-- we can see that most of revenue contribution is coming from young adult which is 62143





